# Modified from https://github.com/probot/stale#usage

# Number of days of inactivity before a stale issue is closed
daysUntilClose: false

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This pull request has been automatically marked as stale because it has not had
  recent activity.
