- hosts: localhost
  connection: local
  vars:
    - rosdistro: galactic
    - rmw_implementation: rmw_cyclonedds_cpp
  roles:
    - role: autoware.dev_env.autoware_core
    - role: autoware.dev_env.docker
    - role: autoware.dev_env.pre_commit
    - role: autoware.dev_env.ros2
    - role: autoware.dev_env.ros2_dev_tools
    - role: autoware.dev_env.rmw_implementation
