- name: Install gdown
  become: true
  ansible.builtin.pip:
    name:
      - gdown
    state: latest

- name: Download archive
  ansible.builtin.command:
    cmd: gdown https://drive.google.com/u/0/uc?id=1eNh3F3xCQ4AMJEHtwb1dhshSyzWMjoc8 -O /tmp/libtorch.zip
    creates: /tmp/libtorch.zip

- name: Unarchive
  become: true
  ansible.builtin.unarchive:
    src: /tmp/libtorch.zip
    dest: /usr/local

- name: Install OpenMP
  become: true
  ansible.builtin.apt:
    name:
      - libgomp1
    state: present
    update_cache: true

- name: Copy library file
  become: true
  ansible.builtin.copy:
    src: /usr/lib/x86_64-linux-gnu/libgomp.so.1
    dest: /usr/local/libtorch/lib/libgomp-75eea7e8.so.1
    mode: preserve

- name: Add LD_LIBRARY_PATH to .bashrc
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: export LD_LIBRARY_PATH="/usr/local/libtorch/lib:$LD_LIBRARY_PATH"
    state: present
