name: docker-build-and-push

on:
  push:
    tags:
      - v*
  schedule:
    - cron: 0 0 1,15 * *
  workflow_dispatch:

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - galactic
          - humble
        include:
          - { rosdistro: galactic, branch: main }
          - { rosdistro: humble, branch: humble }
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Load env
        run: |
          cat amd64.env | sed -e "s/^\s*//" -e "/^#/d" >> $GITHUB_ENV
          if [ "$(uname -m)" = "aarch64" ]; then
            cat arm64.env | sed -e "s/^\s*//" -e "/^#/d" >> $GITHUB_ENV
          fi

      - name: Build 'autoware-universe'
        uses: ./.github/actions/docker-build-and-push
        with:
          bake-target: autoware-universe
          build-args: |
            *.platform=linux/amd64
            *.args.ROS_DISTRO=${{ env.rosdistro }}
            *.args.CUDA_IMAGE_TAG=${{ env.cuda_image_tag }}
            *.args.CUDNN_VERSION=${{ env.cudnn_version }}
            *.args.TENSORRT_VERSION=${{ env.tensorrt_version }}
          tag-prefix: ${{ env.rosdistro }}-
          tag-suffix: -amd64

      - name: Show disk space
        run: |
          df -h
