name: github-release

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag-name:
        type: string
        required: true

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Set tag name
        id: set-tag-name
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG_NAME="${{ github.event.inputs.tag-name }}"
          else
            TAG_NAME="${{ github.ref_name }}"
          fi

          echo ::set-output name=tag-name::"$TAG_NAME"

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ steps.set-tag-name.outputs.tag-name }}

      - name: Run generate-changelog
        id: generate-changelog
        uses: autowarefoundation/autoware-github-actions/generate-changelog@v1

      - name: Release to GitHub
        run: |
          gh release create "${{ steps.set-tag-name.outputs.tag-name }}" \
            --draft \
            --title "Release ${{ steps.set-tag-name.outputs.tag-name }}" \
            --notes "$NOTES"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NOTES: ${{ steps.generate-changelog.outputs.changelog }}
