name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # This can be removed if we'll manage ansible files in another repository.
      - name: Install Ansible Galaxy depends for ansible-lint
        run: |
          ansible-galaxy collection install -f -r ansible-galaxy-requirements.yaml

      - name: Run pre-commit
        uses: autowarefoundation/autoware-github-actions/pre-commit@tier4/proposal
        with:
          pre-commit-config: .pre-commit-config.yaml
