name: setup-universe

on:
  pull_request:

jobs:
  setup-universe:
    runs-on: ubuntu-latest
    container: ubuntu:${{ matrix.ubuntu-version }}
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - galactic
        include:
          - { rosdistro: galactic, ubuntu-version: 20.04 }
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run setup script
        run: |
          ./setup-dev-env.sh -y -v --no-nvidia universe
