name: update-docker-manifest

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update-docker-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Combine multi arch images for 'autoware-universe'
        uses: ./.github/actions/combine-multi-arch-images
        with:
          package-name: autoware-universe

      - name: Create main distro alias for 'autoware-universe'
        uses: ./.github/actions/create-main-distro-alias
        with:
          package-name: autoware-universe
          rosdistro: galactic
